### ISSUE TITLE
Setup Travis CI to validate PRs

### ISSUE THREAD

**Issue by sbose78** [devfile/parser#11]
A minimum " go build ... " would be a good starting point

**Comment by ranakan19** [comment]
Access requested from organization

**Comment by sleshchenko** [comment]
@sbose78 Could we use GitHub Actions for PR checks? In my experience, it's really easy to set up.
I'm OK with Travis as well but would like to know the benefits.

**Comment by sbose78** [comment]
I'm good with that too, Serhii. Would you be able to drop some pointers on that?

**Comment by sbose78** [comment]
We anyway need to do a " go build " and a "go test" so GitHub actions should be easy. 

Kanika, could you take a look at configuring GitHub actions please?

**Comment by sleshchenko** [comment]
https://github.com/actions/setup-go
So, the configuration file should be something like the following

```yaml
name: Docker
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - name: Compile GO
      exec: go build ./main.go
    - name: Run go tests
      exec: go test ./...
```
Let me know if more
