### ISSUE TITLE
Empty Parent introduced 

### ISSUE THREAD

**Issue by ranakan19** [devfile/parser#30]
**Describe the bug**
Parent should not be expected to have a parent. When parsing the parent devfile, empty parent is introduced which causes schema validation failure. 

**To Reproduce**
Checkout PR https://github.com/devfile/parser/pull/28, and run tests in parse_test.go, the test fails with the following error:
	```
       Test_parseParent/case_1:_it_should_override_the_requested_parent's_data_and_add_the_local_devfile's_data (0.01s)
	parse_test.go:608: parseParent() error = invalid devfile schema. errors :
	- parent: Must validate one and only one schema (oneOf)
	- parent: uri is required
	, wantErr false
        ```

	Test_parseParent/case_2:_handle_a_parent'data_without_any_local_override_and_add_the_local_devfile's_data (0.00s)
	parse_test.go:608: parseParent() error = invalid devfile schema. errors :
	- parent: Must validate one and only one schema (oneOf)
	- parent: uri is required
	, wantErr false

**Expected behavior**
Parent should not be introduced within parent. mitEmpty tag only works for structs if it is nilable. Thus the parent should be a pointer reference within devfile Obj struct [here](https://github.com/devfile/parser/blob/master/pkg/devfile/parser/data/2.0.0/types.go#L24)

**Screenshots**
NA

**Additional context**
parentDevfile (go structs) from the test case is generated as yaml file from the test http server here - https://github.com/wtam2018/parser/blob/parser-update/pkg/devfile/parser/parse_test.go#L587
The generated yaml is as below:
```
commands:
- exec:
    commandLine: npm run
    id: devrun
    workingDir: /projects
components:
- container:
    dedicatedPod: false
    image: quay.io/nodejs-10
    mountSources: false
    name: nodejs
    sourceMapping: ""
events:
  postStart:
  - post-start-0
metadata: {}
parent:
  events: {}
projects:
- clonePath: /data
  github:
    branch: master
    sparseCheckoutDir: ""
  name: nodejs-starter
schemaVersion: 2.0.0

```
which introduces a parent with an empty events struct, and thus fails the schema validation since it requires parent to have either Id, uri or Kubernetes - as here - https://github.com/wtam2018/parser/blob/parser-update/pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go#L3636
